# Generated by Django 6.0.7 on 2026-08-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('lifestyle', 'Lifestyle'), ('business', 'Business'), ('tech', 'Tech'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
