# Generated by Django 6.0.7 on 2026-08-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralBlogApp', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
